# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: 'CMake (WSL)'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        build_type: [x64-Debug-Linux, x64-Release-Linux]
        gcc: [10, 11, 12]

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: seanmiddleditch/gha-setup-ninja@96bed6edff20d1dd61ecff9b75cc519d516e6401 # v5

    - name: 'Configure CMake'
      working-directory: ${{ github.workspace }}
      run: >
        cmake --preset=${{ matrix.build_type }}

      env:
        CC: gcc-${{ matrix.gcc }}
        CXX: g++-${{ matrix.gcc }}

    - name: 'Build'
      working-directory: ${{ github.workspace }}
      run: cmake --build out/build/${{ matrix.build_type }}
